# GitHub Actions CI/CD for Pluto Backend - Docker Hub + AKS
name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pluto-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v4
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config get-contexts
      - name: Deploy to AKS
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl apply -f deployment.yaml
          kubectl rollout status deployment/pluto-backend
          kubectl get services
